import { readFile, writeFile, mkdir } from "node:fs/promises";
import { join, resolve } from "node:path";
import { randomUUID } from "node:crypto";
import { writeFileAtomically } from "./atomic-file.js";

export type HandoffMessageType =
  | "task"
  | "handoff"
  | "question"
  | "done"
  | "status"
  | "error"
  | "cancel";

export interface HandoffMessage {
  id: string;
  type: HandoffMessageType;
  from: string;
  to: string;
  description: string;
  context?: string;
  timestamp: string;
}

export interface HandoffState {
  initialized: boolean;
  directory: string;
  messages: HandoffMessage[];
  pending: HandoffMessage[];
  done: HandoffMessage[];
}

const HANDOFF_DIR = ".handoff";
const MESSAGES_FILE = "messages.jsonl";
const PROTOCOL_FILE = "PROTOCOL.md";

function handoffDir(projectRoot: string): string {
  return join(projectRoot, HANDOFF_DIR);
}

function messagesPath(projectRoot: string): string {
  return join(handoffDir(projectRoot), MESSAGES_FILE);
}

export async function isHandoffInitialized(
  projectRoot: string,
): Promise<boolean> {
  try {
    await readFile(join(handoffDir(projectRoot), PROTOCOL_FILE), "utf8");
    return true;
  } catch {
    return false;
  }
}

export async function initHandoff(projectRoot: string): Promise<string> {
  const dir = handoffDir(projectRoot);
  await mkdir(dir, { recursive: true });

  const protocol = [
    "# Handoff Protocol",
    "",
    "This directory enables asynchronous task handoff between AI coding agents.",
    "Generated by `loadout handoff init`. Compatible with the JSONL handoff convention.",
    "",
    "## Message types",
    "",
    "- **task**: assign work to another agent",
    "- **handoff**: transfer in-progress work with context",
    "- **question**: ask another agent for input",
    "- **done**: signal completion",
    "- **status**: progress update",
    "- **error**: report a failure",
    "- **cancel**: withdraw a task",
    "",
    "## Files",
    "",
    "- `messages.jsonl` — append-only message log (one JSON object per line)",
    "- `PROTOCOL.md` — this file",
    "",
    "## Usage",
    "",
    "```",
    "loadout handoff send codex 'write unit tests for auth module'",
    "loadout handoff send claude-code 'review the API changes' --context 'see PR #42'",
    "loadout handoff status",
    "loadout handoff done <message-id>",
    "```",
    "",
    "Agents read this directory on wake. Loadout manages the message log;",
    "each agent's own CLAUDE.md / AGENTS.md can reference .handoff/ for pickup.",
    "",
  ].join("\n");

  await writeFileAtomically(join(dir, PROTOCOL_FILE), protocol);

  // Create empty messages file if it doesn't exist
  try {
    await readFile(messagesPath(projectRoot));
  } catch {
    await writeFile(messagesPath(projectRoot), "", "utf8");
  }

  return dir;
}

export async function sendHandoff(
  projectRoot: string,
  to: string,
  description: string,
  options: {
    from?: string;
    type?: HandoffMessageType;
    context?: string;
  } = {},
): Promise<HandoffMessage> {
  if (!(await isHandoffInitialized(projectRoot))) {
    throw new Error(
      "Handoff not initialized. Run `loadout handoff init` first.",
    );
  }

  const message: HandoffMessage = {
    id: randomUUID().slice(0, 8),
    type: options.type ?? "task",
    from: options.from ?? "user",
    to,
    description,
    ...(options.context ? { context: options.context } : {}),
    timestamp: new Date().toISOString(),
  };

  const path = messagesPath(projectRoot);
  const line = JSON.stringify(message) + "\n";
  await writeFile(path, line, { flag: "a" });

  return message;
}

export async function markDone(
  projectRoot: string,
  messageId: string,
): Promise<HandoffMessage> {
  const messages = await readMessages(projectRoot);
  const original = messages.find((m) => m.id === messageId);
  if (!original) throw new Error(`Message '${messageId}' not found`);
  if (original.type === "done")
    throw new Error(`Message '${messageId}' is already done`);

  return sendHandoff(projectRoot, original.from, `Completed: ${original.description}`, {
    from: original.to,
    type: "done",
    context: `Resolves ${messageId}`,
  });
}

export async function readMessages(
  projectRoot: string,
): Promise<HandoffMessage[]> {
  if (!(await isHandoffInitialized(projectRoot))) return [];
  try {
    const content = await readFile(messagesPath(projectRoot), "utf8");
    return content
      .split("\n")
      .filter(Boolean)
      .map((line) => JSON.parse(line) as HandoffMessage);
  } catch {
    return [];
  }
}

export async function getHandoffState(
  projectRoot: string,
): Promise<HandoffState> {
  const initialized = await isHandoffInitialized(projectRoot);
  const messages = initialized ? await readMessages(projectRoot) : [];

  const doneIds = new Set(
    messages
      .filter((m) => m.type === "done")
      .flatMap((m) => {
        const match = m.context?.match(/Resolves (\w+)/);
        return match ? [match[1]] : [];
      }),
  );

  const pending = messages.filter(
    (m) => m.type === "task" && !doneIds.has(m.id),
  );
  const done = messages.filter(
    (m) => m.type === "task" && doneIds.has(m.id),
  );

  return {
    initialized,
    directory: handoffDir(projectRoot),
    messages,
    pending,
    done,
  };
}

export function formatHandoffStatus(state: HandoffState): string {
  if (!state.initialized) return "Handoff not initialized. Run `loadout handoff init`.";
  if (state.messages.length === 0) return "No handoff messages yet. Send one with `loadout handoff send <agent> <task>`.";

  const lines: string[] = [];

  if (state.pending.length) {
    lines.push(`Pending (${state.pending.length}):`);
    for (const m of state.pending) {
      lines.push(`  ${m.id}  ${m.from} → ${m.to}  ${m.description}`);
    }
  }

  if (state.done.length) {
    if (lines.length) lines.push("");
    lines.push(`Done (${state.done.length}):`);
    for (const m of state.done) {
      lines.push(`  ${m.id}  ${m.from} → ${m.to}  ${m.description}`);
    }
  }

  const other = state.messages.filter(
    (m) => m.type !== "task" && m.type !== "done",
  );
  if (other.length) {
    if (lines.length) lines.push("");
    lines.push(`Other messages: ${other.length}`);
  }

  return lines.join("\n");
}
